### ISSUE TITLE
请问大佬，如何准备数据集进行训练，另外没有./data/seg/balloon.yaml 这个文件

### ISSUE THREAD

**Issue by zhuimeng2080** [Laughing-q/yolov5-q#1]

**Comment by Laughing-q** [comment]
训练集的格式我更新到README.md了，balloon是我自己测试的数据集，我也上传到release了

**Comment by zhuimeng2080** [comment]
您好，


   非常感谢大佬，邮件收到。好的。
















在 2022-04-25 10:02:40，"Laughing" ***@***.***> 写道：

训练集的格式我更新到README.md了，balloon是我自己测试的数据集，我也上传到release了

**Comment by zhuimeng2080** [comment]
您好，


     再请教大佬一下。


     您的框架对于不同场景的裂缝目标的检测与分割的效果如何，好像一般两阶段的检测方法比较好，但是速度慢，也有很少的框架能够有tensorrt进行加速的；单个阶段对于裂缝的精度一般很低，比如不像行人车辆那样，置信度很容易达到0.9以上，裂缝的误检和漏检也非常多。
















在 2022-04-25 16:35:14，"Laughing" ***@***.***> 写道：

Closed #1.

**Comment by Laughing-q** [comment]
我觉得肯定还是二阶段的效果好些，我这个项目目前还只是试验阶段，我也不太清楚在裂缝分割上表现咋样，这个项目最初的目的就是希望能够保证yolov5速度（或者说牺牲少量速度）的情况下去取得一个不错的实例分割精度。所以该项目目前主要还是以速度为主，精度这方面不太保证哈

**Comment by Seperendity** [comment]
@Laughing-q Thank you for your great work, can you please tell me why the coco-seg annotation only has the true values of the segmentation points, but finally after training we can get the detection and segmentation results? The dataset should have the true values of the segmentation points and the true values of the detection frames in order to do the loss calculation separately, right? The same question as ballon datasets.

**Comment by Laughing-q** [comment]
@Seperendity Since the segmentation points are the boundaries of object, we can get the labels of detection by segmentation points with this function:
[https://github.com/Laughing-q/yolov5-q/blob/57d39ddeed2ce03b0017a215faa30778250b0cac/yolov5/utils/segment.py#L10-L20](https://github.com/Laughing-q/yolov5-q/blob/57d39ddeed2ce03b0017a215faa30778250b0cac/yolov5/utils/segment.py#L10-L20)

**Comment by Seperendity** [comment]
Cool, thank you so much! I will follow the project you and&nbsp; AYUSHexel are pushing. That's will be a great work. Lastly, from the experiments you have done, can these two tasks promote each other? I am planning to add depth information in the total loss in the future, do you think the three task will help each other?&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Laughing-q/yolov5-q"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月13日(星期二) 下午4:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Laughing-q/yolov5-q] 请问大佬，如何准备数据集进行训练，另外没有./data/seg/balloon.yaml 这个文件 (Issue #1)





 
@Seperendity Since the segmentation points are the boundaries of object, we can get the labels of detection by segmentation points with this function:
 https://github.com/Laughing-q/yolov5-q/blob/57d39ddeed2ce03b0017a215faa30778250b0cac/yolov5/utils/segment.py#L10-L20

**Comment by Laughing-q** [comment]
@Seperendity Thanks... I'm not so sure to say these tasks promote each other, but we got a little better results with segmentation and detection than with detection only in our experiments.

**Comment by Seperendity** [comment]
@Laughing-q ok, thank you for you patient answer.
